# Generated by Django 2.2.1 on 2019-05-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
