# Generated by Django 2.0.1 on 2018-01-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0006_auto_20180130_0304")]

    operations = [
        migrations.RenameField(model_name="event", old_name="when", new_name="date")
    ]
