# Generated by Django 2.0.1 on 2018-01-30 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0008_auto_20180130_1450")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
