# Generated by Django 2.0.1 on 2018-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_event_slug")]

    operations = [
        migrations.AddField(
            model_name="cult",
            name="slug",
            field=models.CharField(default="default slug", max_length=100),
            preserve_default=False,
        )
    ]
