# Generated by Django 2.0.1 on 2018-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0011_cult_slug")]

    operations = [
        migrations.AlterField(
            model_name="cult",
            name="slug",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
