# Generated by Django 2.0.1 on 2018-01-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180131_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cult',
            name='country',
        ),
    ]
