# Generated by Django 2.0.1 on 2018-02-10 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0019_auto_20180210_1402")]

    operations = [
        migrations.AddField(
            model_name="cult",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
